import io
import contextlib
import os
import json
import logging
import asyncio
from typing import Any, Dict, Union
from fastapi.middleware.cors import CORSMiddleware
from fastapi import FastAPI, Request, Header, Response
import uvicorn
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel
import httpx
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Import ADK components (silently during module load)
try:
    from google.adk.agents import Agent
    from google.adk.runners import InMemoryRunner
    from google.adk.tools import google_search
    from google.genai import types
except ImportError as e:
    print(f"❌ ADK Import Error: {e}")
    raise

# Initialize runner only once
runner = None


def get_runner():
    global runner
    if runner is None:
        # Set up Google GenAI configuration (only once)
        os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "FALSE"
        print("✅ Google GenAI configuration set.")
        print("✅ ADK components imported successfully.")
        
        root_agent = Agent(
            name="helpful_assistant",
            model="gemini-2.5-flash-lite",
            description="A simple agent that can answer general questions.",
            instruction="You are a helpful assistant. Use Google Search for current info or if unsure.",
            tools=[google_search],
        )
        print("✅ Root Agent defined.")
        
        runner = InMemoryRunner(agent=root_agent, app_name="agents")
        print("✅ Runner created.")
    return runner


log = logging.getLogger("test_gen_api")
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")

app = FastAPI(title="Test Generator API")

# Allow your HTML server on 8001 to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:8002"],  # front-end origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class FrontendRequest(BaseModel):
    test_prompt: str  # string from the browser

class FrontendResponse(BaseModel):
    agent_generated_test_data: str      # record generated by agent
    test_results_from_API: str          # results from API under test

@app.post("/generate_test", response_model=FrontendResponse)
async def gen_test(
    payload: FrontendRequest,
    #x_mailhook_token: Union[str, None] = Header(default=None)  # optional: read shared secret header
) -> Response:

    contact_record ="""
    Contact(first_name="Bogdan",
        last_name="Georgescu",
        hebrew_name= "בורגאן גאורגסקו",
        birth_date=datetime(1976,1,16),
        birth_date_day_h=14,
        birth_date_month_h=2, 
        birth_date_year_h=5776, 
        phone_primary="14032829220",    
        phone_secondary="15879669220",  
        email="bageorge1976@gmail.com",
        address="805 80 Point McKay CR NW",
        city="Calgary",
        province="Alberta",
        country="Canada",
        postal_code="T3B4W4",
        notes="A sample contact")  
    
    """

    prompt = payload.test_prompt

    with open("rules.txt", "r", encoding="utf-8") as f:
        rules = f.read()

    agent_generated_test_data: str = ""
    data_from_API_under_test: Dict[str, str] = {"result": ""}

    # Process the text with Google ADK agent
    try:
        # Get the runner (creates it only once)
        current_runner = get_runner()
        
        # Use run_debug with the prompt
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            events = await current_runner.run_debug(prompt)# + " " + rules )
            

        # Take the last event and extract plain text from its parts
        if events:
            last_event = events[-1]
            agent_generated_test_data = "".join(
                (getattr(part, "text", "") or "")
                for part in last_event.content.parts
            )
            log.info("Agent response: %s", agent_generated_test_data)
        else:
            log.warning("No events received from ADK runner")
            
        # Get API URL from environment variables
        api_under_test_url = os.getenv("API_UNDER_TEST_URL")
        if not api_under_test_url:
            raise ValueError("API_UNDER_TEST_URL environment variable is not set")
            
       # Call the API under test with generated test data
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                api_under_test_url,
                json={"record": agent_generated_test_data},  # must be 'record'
            )
            resp.raise_for_status()
            data_from_API_under_test = resp.json()  # keep the real result

    except Exception as e:
        log.error("ADK processing error: %s", str(e))
        if not agent_generated_test_data:
            agent_generated_test_data = f"Error generating test data: {e}"
        if not data_from_API_under_test["result"]:
            data_from_API_under_test["result"] = "Error calling API under test."

    # Build response for frontend (only after B replied)
    return FrontendResponse(
        agent_generated_test_data=agent_generated_test_data,
        test_results_from_API=data_from_API_under_test["result"],
    )

if __name__ == "__main__":
    port = int(os.getenv("PORT", "8090"))
    print(f"Test generator API on :{port}")
    uvicorn.run("test_gen_API:app", host="0.0.0.0", port=port, reload=False)
